import type { Request, Response } from "express"

export const getMockedRequest = (options: Partial<Request> = {}) => ({
  app: {},
  baseUrl: "",
  body: {},
  cookies: {},
  fresh: true,
  headers: {},
  hostname: "",
  ip: "127.0.0.1",
  ips: [],
  method: "GET",
  originalUrl: "",
  params: {},
  path: "",
  protocol: "https",
  query: {},
  route: {},
  secure: true,
  signedCookies: {},
  stale: false,
  subdomains: [],
  xhr: true,
  accepts: jest.fn(),
  acceptsCharsets: jest.fn(),
  acceptsEncodings: jest.fn(),
  acceptsLanguages: jest.fn(),
  get: jest.fn(),
  is: jest.fn(),
  range: jest.fn(),
  ...options,
})

export const getMockedResponse = (options: Partial<Response> = {}) => {
  const res = {
    app: {},
    headersSent: false,
    locals: {},
    append: jest.fn(),
    attachment: jest.fn(),
    clearCookie: jest.fn(),
    download: jest.fn(),
    end: jest.fn(),
    format: jest.fn(),
    json: jest.fn(),
    jsonp: jest.fn(),
    links: jest.fn(),
    location: jest.fn(),
    redirect: jest.fn(),
    render: jest.fn(),
    send: jest.fn(),
    sendFile: jest.fn(),
    sendStatus: jest.fn(),
    set: jest.fn(),
    setHeader: jest.fn(),
    type: jest.fn(),
    get: jest.fn(),
    getHeader: jest.fn(),
    ...options,
  } as Record<keyof Response, any>

  return res
}
